# Generated by Django 2.0.2 on 2020-10-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bbody',
            new_name='description',
        ),
    ]
