# Generated by Django 2.0.2 on 2020-10-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201027_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='body',
        ),
    ]
